sylius_twig_hooks:
    hooks:
        'sylius_shop.checkout.select_shipping.content.form':
            ppl_javascripts:
                template: '@ThreeBRSSyliusPplParcelshopsPlugin/Shop/_javascripts.html.twig'
                priority: 200
