sylius_twig_hooks:
    hooks:
        'sylius_shop.checkout.select_shipping.content.form':
            ppl_javascripts:
                template: '@ThreeBRSSyliusPplParcelshopsPlugin/Shop/_javascripts.html.twig'
                priority: 200

        # PPL parcelshop selector after each shipping method choice
        'sylius_shop.checkout.select_shipping.content.form.shipments.shipment.choice':
            ppl_selector:
                template: '@ThreeBRSSyliusPplParcelshopsPlugin/Shop/Checkout/SelectShipping/_pplSelector.html.twig'
                priority: -100

        # Override shipping address in order summary to show PPL parcelshop info
        'sylius_shop.shared.order.show.summary.addresses.shipping.body':
            address:
                template: '@ThreeBRSSyliusPplParcelshopsPlugin/Shop/Common/Order/_shippingAddress.html.twig'
                priority: 0
