services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    # Behat Context Services
    sylius_ppl_parcelshops_plugin.context.setup.shipping_method:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Context\Setup\ShippingMethodContext
        arguments:
            $syliusOrderCheckoutWorkflow: '@state_machine.sylius_order_checkout'

    sylius_ppl_parcelshops_plugin.context.ui.admin.shipping_method:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Context\Ui\Admin\ManagingShippingMethodContext

    sylius_ppl_parcelshops_plugin.context.ui.shop.ppl:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Context\Ui\Shop\ManagingPplContext

    sylius_ppl_parcelshops_plugin.context.ui.admin.shipment_export:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Context\Ui\Admin\ManagingShipmentExportContext

    # Page objects
    sylius_ppl_parcelshops_plugin.page.admin.shipping_method.update:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Page\Admin\ShippingMethod\UpdatePage
        parent: sylius.behat.page.admin.shipping_method.update

    sylius_ppl_parcelshops_plugin.page.admin.shipment_export.index:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Page\Admin\ShipmentExport\IndexPage

    sylius_ppl_parcelshops_plugin.page.shop.ppl:
        class: Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Page\Shop\Ppl\PplPages

    Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Page\Admin\ShippingMethod\UpdatePageInterface: '@sylius_ppl_parcelshops_plugin.page.admin.shipping_method.update'
    Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Page\Admin\ShipmentExport\IndexPageInterface: '@sylius_ppl_parcelshops_plugin.page.admin.shipment_export.index'
    Tests\ThreeBRS\SyliusPplParcelshopsPlugin\Behat\Page\Shop\Ppl\PplPagesInterface: '@sylius_ppl_parcelshops_plugin.page.shop.ppl'
