parameters:
    threebrs_sylius_ppl_parcelshops_plugin_ppl_shipping_method_codes: [ 'ppl_parcel_shop' ]
    # https://ppl-widget-e.apidog.io/configuration-parameters-863668m0
    threebrs_sylius_ppl_parcelshops_plugin_ppl_countries: [ 'CZ', 'SK', 'DE', 'PL', 'HU', 'BG' , 'RO', 'NL', 'AT' ]

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    ThreeBRS\SyliusPplParcelshopsPlugin\Form\Extension\ShipmentPplExtension:
        arguments:
            $allowedCountries: '%threebrs_sylius_ppl_parcelshops_plugin_ppl_countries%'
        tags:
            -   name: form.type_extension
                extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\ShipmentType

    ThreeBRS\SyliusPplParcelshopsPlugin\Form\Extension\AdminPplShippingMethodExtension:
        arguments:
            $countryChoices: '%threebrs_sylius_ppl_parcelshops_plugin_ppl_countries%'
        tags:
            -   name: form.type_extension
                extended_type: Sylius\Bundle\ShippingBundle\Form\Type\ShippingMethodType

    ThreeBRS\SyliusPplParcelshopsPlugin\Model\PplShipmentExporter:
        public: true
        arguments:
            $pplShippingMethodsCodes: '%threebrs_sylius_ppl_parcelshops_plugin_ppl_shipping_method_codes%'
        tags:
            -   name: threebrs.shipment_exporter_type
                type: 'ppl_parcel_shop'
                label: 'PPL ParcelShop'

    ThreeBRS\SyliusPplParcelshopsPlugin\Controller\PplController:
        public: true
        tags:
            - 'controller.service_arguments'
