#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "${DIR}/_tty.sh"

if [ "$(docker compose ps mysql | grep --count Up)" -gt 0 ]; then
    docker_compose_exec \
        mysql \
        mysql -h127.0.0.1 -uroot -pmysql "$@"
else
    docker_compose_run \
        mysql \
        mysql -h127.0.0.1 -uroot -pmysql "$@"
fi
